### ISSUE TITLE
ECS Fargate schedule on 24/7 runnning tasks

### ISSUE THREAD

**Issue by jinfanzon** [cn-terraform/terraform-aws-ecs-fargate-scheduled-task#22]
Hi Julian! - I have a couple of fargate tasks that are currently running on a 24/7 basis. We would like to schedule a start/stop time on this fargate tasks. Would this module be helpful to achieve this? I was not able to set the cron correctly.

Regards

**Comment by jnonino** [comment]
Hi José, just to check if I fully understand your scenario, you have tasks running 24/7 (all the time) but instead of that you want to run them on some schedule, for example every day at 7 AM, is that the use case?

If that's the case, then this module can help you achieve that, you'll need to have an [ECS Cluster](https://registry.terraform.io/modules/cn-terraform/ecs-cluster), a [Task Definition](https://registry.terraform.io/modules/cn-terraform/ecs-fargate-task-definition) and use this module to set a cron expression and run the task on schedule.

This [AWS doc](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-create-rule-schedule.html#eb-cron-expressions) shows how to define the cron expression. For example, the expression `cron(0 20 * * ? *)` means that the task will run at 8:00 PM (UTC+0) every day.

Hope this is helpful, let me know if you have more questions and every change, fix, new feature, or any proposal feel free to submit a PR and I will merge it and release as soon as possible.

**Comment by jinfanzon** [comment]
Thanks Julian! - That is exactly what I need
